ci: execute on merge to main & conclusion (#137)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,5 +1,8 @@
 name: CI
 on:
+  push:
+    branches:
+      - main
   pull_request:
   workflow_dispatch:
 
@@ -22,24 +25,51 @@ jobs:
     uses: ./.github/workflows/cpp.yaml
 
   python:
-      name: Python build and test
-      needs: [cpp]
-      uses: ./.github/workflows/python.yaml
+    name: Python build and test
+    needs: [cpp]
+    uses: ./.github/workflows/python.yaml
 
   coverage:
     name: Code coverage
-    needs: [cpp]
+    needs: [linting]
     uses: ./.github/workflows/coverage.yaml
     secrets: inherit
 
   static_analysis:
     name: Static analysis
-    needs: [cpp]
+    needs: [linting]
     uses: ./.github/workflows/sonarcloud.yaml
     secrets: inherit
 
   benchmarks:
-      name: Benchmarks
-      needs: [cpp, python]
-      uses: ./.github/workflows/benchmarks.yaml
-      secrets: inherit
+    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
+    name: Benchmarks
+    needs: [cpp, python]
+    uses: ./.github/workflows/benchmarks.yaml
+    secrets: inherit
+
+  conclusion:
+    name: Conclusion
+    if: always()
+    needs:
+      - pre-commit
+      - linting
+      - cpp
+      - python
+      - coverage
+      - static_analysis
+      - benchmarks
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Exit on failure
+        if: >-
+          contains(needs.*.result, 'failure') ||
+          contains(needs.*.result, 'cancelled') ||
+          (needs.benchmarks.result == 'failure')
+        run: |
+          echo "❌ Some required jobs failed"
+          exit 1
+
+      - name: Success message
+        run: |
+          echo "✅ All required jobs completed successfully"
